language: go
go:
  - release
  - tip
install: go get -d -t -v ./...
script: go test -v -covermode=count -coverprofile=profile.cov
after_success:
  - go get -v github.com/mattn/goveralls
  - export PATH=$PATH:$HOME/gopath/bin
  - goveralls -coverprofile=profile.cov -service=travis-ci
