language: go
go:
  - 1.3
  - release
  - tip
install:
  - go get -d -t -v ./...
  - if [ "$TRAVIS_GO_VERSION" = "1.3" ]; then go get -v code.google.com/p/go.tools/cmd/vet; else go get -v golang.org/x/tools/cmd/vet; fi
  - go get -v github.com/GeertJohan/fgt
  - go get -v github.com/golang/lint/golint
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - go vet
  - fgt golint -min_confidence=0.9 .
  - go test -v
